[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-Gruvbox
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-Gruvbox
GtkTheme=oomox-Gruvbox
IconTheme=oomox-Gruvbox
MetacityTheme=oomox-Gruvbox
