#!/bin/bash
#xrandr --newmode "75hz Overclock" 151.25 1600 1704 1872 2144 900 903 908 942 -hsync +vsync
#xrandr --addmode eDP-1 "75hz Overclock"
#xrandr --output eDP-1 --mode "75hz Overclock" --rate 75

sxhkd -c ~/.config/openbox/sxhkd &
polybar -r top2 &
xfce4-panel &
pcmanfm --desktop &
# Load Xresources Config
xrdb -merge ~/.Xresources
# Load Custom Keymapping
#xmodmap ~/.Xmodmap
# Disable Screen Timeout
xset -dpms
xset s off
# Enable USB Automount
udiskie -a -t &
# Set Volume To %10
amixer set Master 10%
# Start Policy Daemon
lxqt-policykit-agent &
# Start Compton Screen Composition
#compton --config ~/.config/openbox/compton.conf &
# Set Mouse Timeout To 1 Second

# Set Xorg Cursor Theme
xsetroot -cursor_name left_ptr &
# Start Notofication Daemon
sh ~/Git/scripts/dunst.sh &
sh ~/Git/scripts/double_click.sh &
sh ~/Git/scripts/double_click.sh &
#sh ~/.config/bspwm/wal &
# Disable ethernet port to save battery
sudo ip link set enp0s25 down
# Torrent Client

