#!/bin/bash

PATH=$PATH:$HOME/git/scripts
export PATH
#floating.sh &
# Set Screen Refresh Rate
#xrandr -r 144

# Set Wallpaper
sh ~/.fehbg

# Top and bottom bars
polybar -r top &
polybar -r bottom &

# Bluetooth
blueman-applet &

# Fix java applications
wmname LG3D

# Load Xresources Config
xrdb -merge ~/.Xresources

# Load Custom Keymapping
xmodmap ~/.Xmodmap

# Disable Screen Timeout
#xset -dpms
#xset s off

# Enable USB Automount
udiskie -a -t &

# Set Volume To %10
amixer set Master 10%

# Start Policy Daemon
lxqt-policykit-agent &

# Start Compton Screen Composition
#compton --config ~/.config/compton/solid.conf &

# Set Mouse Timeout To 1 Second
unclutter --timeout 1 &

# Set Xorg Cursor Theme
xsetroot -cursor_name left_ptr &

# Start Notification Daemon
sh ~/git/scripts/dunst.sh &


#bspc config bottom_padding 40
/usr/bin/xcalib -d :0 ~/git/homebase/config/MonitorProfiles/laptop.icm

syncthing &

# Hide Bar
#sh /usr/local/bin/bar.sh
syncthing-gtk &
