#!/bin/bash
# _____  _              _       _____       _    _  _
#|   __||_| _____  ___ | | _ _ |   __| _ _ | |_ | ||_| _____  ___
#|__   || ||     || . || || | ||__   || | || . || || ||     || -_|
#|_____||_||_|_|_||  _||_||_  ||_____||___||___||_||_||_|_|_||___|
#

sudo localedef -f UTF-8 -i en_US en_US.UTF-8

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"
#xrandr --output eDP1 --off
#xrandr --output DP1 --mode 1920x1080 --rate 144
bspc monitor -d 1 2 3 4 5


# Gaps, padding, and size
bspc config border_width 2
bspc config window_gap 5
bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config single_monocle      true
bspc config history_aware_focus true
#bspc config swallow_first_click true
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config initial_polarity second_child


# Border colors
bspc config presel_feedback_color "#b2b602"
bspc config normal_border_color "#282828"
bspc config focused_border_color "#b2b602"
bspc config focus_follows_pointer false

# Resize and move windows with mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus any

# Window rules

bspc rule -a scratchterm sticky=on state=floating hidden=on
bspc rule -a Zathura state=tiled
bspc rule -a Grsync state=tiled

# Launch keybinding daemon
sxhkd &

# Autostart
"$BSPWM_CONFIG/autostart" &
