#!/bin/bash

wal_steam -w

cd ~/.config/qutebrowser
python3 reload.py

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color2"

sh ~/git/rice/scripts/dunst_wal &

cd ~/git/wal-discord
./wal-discord

