#!/bin/bash

# __       _     _           
#/ _\_   _| |__ | |__  _   _ 
#\ \| | | | '_ \| '_ \| | | |
#_\ \ |_| | |_) | |_) | |_| |
#\__/\__,_|_.__/|_.__/ \__, |
#                      |___/ 

PATH=$PATH:$HOME/git/scripts
export PATH

# Set Wallpaper
sh ~/.fehbg


# Top and bottom bars
polybar -r top &
polybar -r bottom &

# Fix java applications
wmname LG3D

# Load Xresources Config
xrdb -merge ~/.Xresources

# Load Custom Keymapping
xmodmap ~/.Xmodmap

# Disable Screen Timeout
#xset -dpms
#xset s off

# Enable USB Automount
udiskie -t &

# Set Volume To %10
amixer set Master 10%

# Start Policy Daemon
lxqt-policykit-agent &

# Start Compton Screen Composition
compton --config ~/.config/compton/compton.conf &

# Set Mouse Timeout To 1 Second
unclutter --timeout 1 &

# Set Xorg Cursor Theme
xsetroot -cursor_name left_ptr &

# Start Notification Daemon
dunst -config ~/.config/dunst/dunstrc &

#bspc config bottom_padding 40
#/usr/bin/xcalib -d :0 ~/git/homebase/config/MonitorProfiles/laptop.icm

syncthing &

# Hide Bar
#sh /usr/local/bin/bar.sh
#syncthing-gtk &
